[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sub_service = "AbTt5oYWeBDh6qkYN4YPgEkL3gom81CXMW73tDctr85K"

[programs.devnet]
sub_service = "AbTt5oYWeBDh6qkYN4YPgEkL3gom81CXMW73tDctr85K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/olha/.config/solana/id.json"

[scripts]
test = "yarn run jest"
