[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sub_service = "2wivZHNNjvwWgrQEkGvv1bH9HgaWxXmfogkB24z1tsJz"

[programs.devnet]
sub_service = "2wivZHNNjvwWgrQEkGvv1bH9HgaWxXmfogkB24z1tsJz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/olha/.config/solana/id.json"

[scripts]
test = "yarn run jest"
